load("@llvm//:defs.bzl", "exec_test")
load("@rules_go//go:def.bzl", "go_binary", "go_test")

package(default_visibility = ["//visibility:public"])

go_binary(
    name = "msvc_action_assert",
    srcs = ["main.go"],
    pure = "on",
)

exec_test(
    name = "test",
    srcs = [
        "main.go",
        "main_test.go",
    ],
    pure = "on",
    rule = go_test,
)
