load("@llvm//:defs.bzl", "exec_test")
load("@llvm//toolchain/runtimes:cc_runtime_binary.bzl", "cc_runtime_stage1_hosted_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "case_insensitive_copy_lib",
    srcs = ["copy.c"],
    hdrs = ["copy.h"],
    deps = ["//tools/case_insensitive_filesystem:common"],
)

cc_runtime_stage1_hosted_binary(
    name = "case_insensitive_copy",
    srcs = ["main.c"],
    deps = ["case_insensitive_copy_lib"],
)

exec_test(
    name = "test",
    srcs = ["copy_test.cc"],
    rule = cc_test,
    deps = [
        "case_insensitive_copy_lib",
        "//tools/case_insensitive_filesystem:common",
    ],
)

exec_test(
    name = "cli_test",
    srcs = ["cli_test.sh"],
    env = {"COPY_TOOLS": "$(rootpaths case_insensitive_copy)"},
    rule = sh_test,
    tools = ["case_insensitive_copy"],
)
