load("@rules_cc//cc/toolchains:args.bzl", "cc_args")
load("@rules_cc//cc/toolchains/impl:documented_api.bzl", "cc_args_list")
load("//windows:versions.bzl", "MSVC_COMPATIBILITY_VERSION")

package(default_visibility = ["//toolchain/args/windows:__pkg__"])

cc_args(
    name = "compatibility",
    actions = [
        "@rules_cc//cc/toolchains/actions:lto_backend",
        "@rules_cc//cc/toolchains/actions:source_compile_actions",
    ],
    args = [
        "/clang:-fms-compatibility-version={}".format(MSVC_COMPATIBILITY_VERSION),
    ],
)

cc_args(
    name = "reproducible_coff_objects",
    actions = [
        "@rules_cc//cc/toolchains/actions:source_compile_actions",
    ],
    args = ["/Brepro"],
)

cc_args(
    name = "windows_sdk_compile_defines",
    actions = [
        "@rules_cc//cc/toolchains/actions:source_compile_actions",
    ],
    args = ["/DNOMINMAX"],
)

cc_args(
    name = "msvc_crt_compile_defines",
    actions = [
        "@rules_cc//cc/toolchains/actions:source_compile_actions",
    ],
    args = [
        "/D_CRT_NONSTDC_NO_WARNINGS",
        "/D_CRT_SECURE_NO_DEPRECATE",
        "/D_CRT_SECURE_NO_WARNINGS",
        "/D_CRT_STDIO_ISO_WIDE_SPECIFIERS",
    ],
)

cc_args(
    name = "reproducible_codeview",
    actions = [
        "@rules_cc//cc/toolchains/actions:source_compile_actions",
    ],
    args = ["/clang:-gno-codeview-command-line"],
)

cc_args(
    name = "target_machine_link_flags",
    actions = ["@rules_cc//cc/toolchains/actions:link_actions"],
    args = select({
        "//platforms/config:windows_x86_64_msvc": [
            "/clang:-Xlinker",
            "/clang:/MACHINE:X64",
        ],
        "//platforms/config:windows_aarch64_msvc": [
            "/clang:-Xlinker",
            "/clang:/MACHINE:ARM64",
        ],
        "//conditions:default": [],
    }),
)

cc_args(
    name = "deterministic_link_flags",
    actions = ["@rules_cc//cc/toolchains/actions:link_actions"],
    args = [
        "/Brepro",
        "/clang:-Xlinker",
        "/clang:/INCREMENTAL:NO",
        "/clang:-Xlinker",
        "/clang:/lldignoreenv",
        "/clang:-Xlinker",
        "/clang:/PDBALTPATH:%_PDB%",
        "/clang:-Xlinker",
        "/clang:/pdbsourcepath:.",
    ],
)

cc_args(
    name = "default_console_subsystem_link_flags",
    actions = ["@rules_cc//cc/toolchains/actions:link_executable_actions"],
    args = [
        "/clang:-Xlinker",
        "/clang:/SUBSYSTEM:CONSOLE",
    ],
)

cc_args(
    name = "libcxx_include",
    actions = [
        "@rules_cc//cc/toolchains/actions:source_compile_actions",
    ],
    args = select({
        "//toolchain:runtimes_all": ["/imsvc{libcxx_include}"],
        "//conditions:default": [],
    }),
    data = select({
        "//toolchain:runtimes_all": ["//runtimes/cxxstdlib:headers_include_search_directory"],
        "//conditions:default": [],
    }),
    format = {
        "libcxx_include": "//runtimes/cxxstdlib:headers_include_search_directory",
    },
)

cc_args(
    name = "sdk_case_overlay",
    actions = [
        "@rules_cc//cc/toolchains/actions:source_compile_actions",
    ],
    args = [
        "/clang:-ivfsoverlay",
        "/clang:{sdk_case_overlay}",
    ],
    data = ["//windows:msvc_sdk_case_overlay"],
    format = {
        "sdk_case_overlay": "//windows:msvc_sdk_case_overlay",
    },
)

cc_args(
    name = "sdk_includes",
    actions = [
        "@rules_cc//cc/toolchains/actions:source_compile_actions",
    ],
    allowlist_include_directories = [
        "//windows:msvc_com_support_headers",
        "//windows:msvc_vcruntime_headers",
        "//windows:winsdk_shared_include",
        "//windows:winsdk_ucrt_include",
        "//windows:winsdk_um_include",
        "//windows:winsdk_winrt_include",
    ],
    args = [
        "/imsvc{msvc_com_support_include}",
        "/imsvc{msvc_include}",
        "/imsvc{winsdk_ucrt_include}",
        "/imsvc{winsdk_shared_include}",
        "/imsvc{winsdk_um_include}",
        "/imsvc{winsdk_winrt_include}",
    ],
    data = [
        "//windows:msvc_com_support_headers",
        "//windows:msvc_vcruntime_headers",
        "//windows:winsdk_shared_include",
        "//windows:winsdk_ucrt_include",
        "//windows:winsdk_um_include",
        "//windows:winsdk_winrt_include",
    ],
    format = {
        "msvc_com_support_include": "//windows:msvc_com_support_headers",
        "msvc_include": "//windows:msvc_vcruntime_headers",
        "winsdk_shared_include": "//windows:winsdk_shared_include",
        "winsdk_ucrt_include": "//windows:winsdk_ucrt_include",
        "winsdk_um_include": "//windows:winsdk_um_include",
        "winsdk_winrt_include": "//windows:winsdk_winrt_include",
    },
)

cc_args(
    name = "msvc_com_support_library_path",
    actions = [
        "@rules_cc//cc/toolchains/actions:link_actions",
    ],
    args = [
        "/clang:-Xlinker",
        "/clang:/LIBPATH:{msvc_com_support_lib}",
    ],
    data = ["//windows:msvc_com_support_libraries"],
    format = {
        "msvc_com_support_lib": "//windows:msvc_com_support_libraries",
    },
)

cc_args(
    name = "msvc_dynamic_runtime_library_path",
    actions = [
        "@rules_cc//cc/toolchains/actions:link_actions",
    ],
    args = [
        "/clang:-Xlinker",
        "/clang:/LIBPATH:{msvc_dynamic_lib}",
    ],
    data = ["//windows:msvc_dynamic_runtime_libraries"],
    format = {
        "msvc_dynamic_lib": "//windows:msvc_dynamic_runtime_libraries",
    },
)

cc_args(
    name = "msvc_static_runtime_library_path",
    actions = [
        "@rules_cc//cc/toolchains/actions:link_actions",
    ],
    args = [
        "/clang:-Xlinker",
        "/clang:/LIBPATH:{msvc_static_lib}",
    ],
    data = ["//windows:msvc_static_runtime_libraries"],
    format = {
        "msvc_static_lib": "//windows:msvc_static_runtime_libraries",
    },
)

cc_args(
    name = "sdk_library_paths",
    actions = [
        "@rules_cc//cc/toolchains/actions:link_actions",
    ],
    args = [
        "/clang:-Xlinker",
        "/clang:/LIBPATH:{winsdk_ucrt_lib}",
        "/clang:-Xlinker",
        "/clang:/LIBPATH:{winsdk_um_lib}",
    ],
    data = [
        "//windows:winsdk_ucrt_libraries",
        "//windows:winsdk_um_libraries",
    ],
    format = {
        "winsdk_ucrt_lib": "//windows:winsdk_ucrt_libraries",
        "winsdk_um_lib": "//windows:winsdk_um_libraries",
    },
)

cc_args_list(
    name = "sdk_compile_args",
    args = [
        "windows_sdk_compile_defines",
        "sdk_case_overlay",
        "sdk_includes",
    ],
    visibility = ["//visibility:public"],
)

cc_args_list(
    name = "default_libs",
    args = [
        "sdk_library_paths",
        "msvc_com_support_library_path",
    ] + select({
        "//toolchain/features/msvc:static_crt_config": ["msvc_static_runtime_library_path"],
        "//conditions:default": ["msvc_dynamic_runtime_library_path"],
    }),
)
