load("@llvm//:defs.bzl", "exec_test")
load("@llvm//toolchain/runtimes:cc_runtime_binary.bzl", "cc_runtime_complete_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "windows_case_vfs_lib",
    srcs = ["vfs.cc"],
    hdrs = ["vfs.h"],
    deps = ["//tools/windows_case:common"],
)

cc_runtime_complete_binary(
    name = "windows_case_vfs",
    srcs = ["main.cc"],
    deps = ["windows_case_vfs_lib"],
)

exec_test(
    name = "test",
    srcs = ["vfs_test.cc"],
    rule = cc_test,
    deps = [
        "windows_case_vfs_lib",
        "//tools/windows_case:common",
    ],
)
