load("@bazel_lib//:bzl_library.bzl", "bzl_library")
load("@llvm//toolchain:selects.bzl", "platform_llvm_binary")
load("@llvm//tools:defs.bzl", "TOOLCHAIN_BINARIES")
load("@rules_python//python:defs.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])

[
    alias(
        name = tool,
        actual = platform_llvm_binary(tool),
        tags = ["manual"],
    )
    for tool in TOOLCHAIN_BINARIES
]

py_binary(
    name = "update_osx_sdk",
    srcs = ["update_osx_sdk.py"],
    main = "update_osx_sdk.py",
    python_version = "PY3",
    tags = ["manual"],
)

alias(
    name = "msvc_action_assert",
    actual = "//tools/msvc_action_assert",
)

test_suite(
    name = "msvc_action_assert_test",
    tests = ["//tools/msvc_action_assert:test"],
)

alias(
    name = "msvc_artifact_assert",
    actual = "//tools/msvc_artifact_assert",
)

test_suite(
    name = "msvc_artifact_assert_test",
    tests = ["//tools/msvc_artifact_assert:test"],
)

alias(
    name = "msvc_tool_probe",
    actual = "//tools/msvc_tool_probe",
)

test_suite(
    name = "msvc_tool_probe_test",
    tests = ["//tools/msvc_tool_probe:test"],
)

bzl_library(
    name = "defs",
    srcs = ["defs.bzl"],
)
