"""Analysis coverage for `layering_check` alongside named C++20 modules.

These tests inspect the compiler actions that Bazel registers; they do not need
to compile deliberately invalid source files. This makes the tests specifically
about toolchain feature composition and the resulting Clang command line.

Two different module mechanisms need to coexist:

* `layering_check` uses Clang header modules and Bazel-generated `.cppmap`
  module maps to enforce which declared headers a source may include.
* `cpp_modules` uses C++20 named modules, BMIs (`.pcm` files), and a generated
  `.modmap` response file that tells Clang where imported BMIs are located.

The tests below cover an ordinary C++ source, a named-module interface, and an
ordinary C++ source that imports a named module. The last case needs both
mechanisms at the same time.
"""

load("@bazel_skylib//lib:unittest.bzl", "analysistest", "asserts")

def _compile_action(env):
    # `target_actions` exposes the actions registered directly by the configured
    # target under test. Both ordinary C++ compilation and named-module
    # compilation currently use the `CppCompile` mnemonic.
    actions = [
        action
        for action in analysistest.target_actions(env)
        # Ignore CppCompile-shaped validation actions that discard their output;
        # the assertions below concern the real object/BMI-producing action.
        if action.mnemonic == "CppCompile" and action.argv and action.argv[-3:-1] != ["-o", "/dev/null"]
    ]
    asserts.equals(env, 1, len(actions), "expected one CppCompile action")
    return actions[0] if actions else None

def _ordinary_layering_check_flags_test_impl(ctx):
    """Checks a C++20 source that uses headers but does not use named modules."""
    env = analysistest.begin(ctx)
    action = _compile_action(env)
    if action:
        argv = action.argv

        # These are the Clang header-module checks used by `layering_check`.
        # Bazel's generated module maps describe the target's own headers and
        # the headers made available by its declared dependencies.
        asserts.true(env, "-fmodules-strict-decluse" in argv)
        asserts.true(env, "-Wprivate-header" in argv)
        asserts.true(env, any([arg.startswith("-fmodule-map-file=") for arg in argv]))

        # In C++20 mode Clang otherwise treats module-map modules as C++
        # modules. This target does not use Bazel's `cpp_modules` feature, so
        # force the maps back to the Clang header-module behavior expected by
        # `layering_check`.
        asserts.true(env, "-fno-cxx-modules" in argv)
    return analysistest.end(env)

ordinary_layering_check_flags_test = analysistest.make(
    _ordinary_layering_check_flags_test_impl,
    config_settings = {
        "//command_line_option:features": ["layering_check"],
    },
)

def _cpp20_module_layering_check_flags_test_impl(ctx):
    """Checks the action that produces a C++20 named-module BMI."""
    env = analysistest.begin(ctx)
    action = _compile_action(env)
    if action:
        argv = action.argv

        # `direct_module.cppm` is a named-module interface. Its compile action
        # must produce a BMI, and C++ modules must remain enabled for that to
        # work even when the build globally requests `layering_check`.
        asserts.true(env, any([arg.startswith("-fmodule-output=") for arg in argv]))
        asserts.false(env, "-fno-cxx-modules" in argv)

        # `layering_check` is defined for ordinary compile actions. It must not
        # turn the named-module interface compile into a Clang header-module
        # compile by adding the strict-declaration-use check.
        asserts.false(env, "-fmodules-strict-decluse" in argv)
    return analysistest.end(env)

cpp20_module_layering_check_flags_test = analysistest.make(
    _cpp20_module_layering_check_flags_test_impl,
    config_settings = {
        "//command_line_option:features": ["layering_check"],
    },
)

def _cpp20_module_consumer_layering_check_flags_test_impl(ctx):
    """Checks an ordinary source that imports a C++20 named module."""
    env = analysistest.begin(ctx)
    action = _compile_action(env)
    if action:
        argv = action.argv

        # The consumer is an ordinary .cc compile, so `layering_check` still
        # supplies and enforces the header module maps for its declared deps.
        asserts.true(env, "-fmodules-strict-decluse" in argv)
        asserts.true(env, any([arg.startswith("-fmodule-map-file=") for arg in argv]))

        # The response file is separate named-module plumbing generated by
        # Bazel. It maps imports to the BMIs produced by module dependencies.
        asserts.true(env, any([arg.startswith("@") and arg.endswith(".modmap") for arg in argv]))

        # Although this is an ordinary .cc action, it imports `direct_module`.
        # Disabling C++ modules here would preserve layering_check but break the
        # named-module import. This is the key coexistence assertion.
        asserts.false(env, "-fno-cxx-modules" in argv)
    return analysistest.end(env)

cpp20_module_consumer_layering_check_flags_test = analysistest.make(
    _cpp20_module_consumer_layering_check_flags_test_impl,
    config_settings = {
        "//command_line_option:features": ["layering_check"],
    },
)

def layering_check_test_suite():
    """Instantiates the three feature-composition analysis tests."""

    # Baseline: ordinary C++20 compilation uses only header/module-map based
    # layering enforcement.
    ordinary_layering_check_flags_test(
        name = "ordinary_layering_check_flags_test",
        target_under_test = ":layering_check_consumer",
    )

    # Producer: a .cppm action builds a named-module BMI and must not be forced
    # into header-module-only mode.
    cpp20_module_layering_check_flags_test(
        name = "cpp20_module_layering_check_flags_test",
        target_under_test = ":direct_module",
    )

    # Consumer: an ordinary .cc action simultaneously uses layering-check
    # module maps and imports the named module produced above.
    cpp20_module_consumer_layering_check_flags_test(
        name = "cpp20_module_consumer_layering_check_flags_test",
        target_under_test = ":direct_module_test",
    )
