name: LLVM Prebuilt Memory Test

on:
  push:
    branches:
      - "llvm-*"
  workflow_dispatch:

permissions:
  attestations: write
  contents: write
  artifact-metadata: write
  id-token: write

concurrency:
  group: llvm-prebuilt-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Mount bazel caches
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.cache/bazel-repo
          key: llvm-prebuilt-bazel-${{ runner.os }}-${{ github.ref_name }}
          restore-keys: |
            llvm-prebuilt-bazel-${{ runner.os }}

      - name: Build and package prebuilts
        id: build_and_package
        run: /usr/bin/time -v bash .github/workflows/llvm-prebuilt.sh
